### ISSUE TITLE
ANALYTICS

### ISSUE THREAD

**Issue by S3BzA** [COS301-SE-2024/Dispute-Resolution-Engine#183]
Use classification, date & time, logging metrics to drive statistical analysis.
Classification (KNN): gzip classification
Idea: What kind of disputes are users often involved in?
![image](https://github.com/COS301-SE-2024/Dispute-Resolution-Engine/assets/81089003/ad8b0006-6da2-44d7-a925-9af14716650d)

Frontend:
- [x] Dashboard
- [x]  [ApexCharts](https://apexcharts.com/) for graphing

Services:
- [x] Statistical queries (time, category, etc.)
- [ ] Logging & Parsing logs
- [ ] Classification

Database:
- [ ] Enumerate metrics for entities

**Comment by ghost** [comment]
We will be splitting this up into more granular features
