### ISSUE TITLE
Stub endpoint for dispute list

### ISSUE THREAD

**Issue by ghost** [COS301-SE-2024/Dispute-Resolution-Engine#38]
Create an endpoint (to be extended later) that returns a summary view of all the disputes for a user. A sample response could look like:
```json
[
  {
    "id": "id of dispute",
    "title": "Title of the dispute",
  },
  ...
]
```

**Comment by CaelanHill** [comment]
I implimented a stubbed v1 of this function. Check if you are happy with it.
