### ISSUE TITLE
Add a database table for rendering a dispute decision

### ISSUE THREAD

**Issue by ghost** [COS301-SE-2024/Dispute-Resolution-Engine#460]
To facilitate experts resolving a dispute, we need a table to store the decisions rendered by experts, called `dispute_decisions`. Some initial attributes I could think of:
- ID of the dispute and expert submitting the writeup
- A reference to the writeup file used for the dispute
- The decision rendered by the writeup
- The date that the writeup was submitted

This also presents some triggers that need to be implemented. When a writeup is submitted,:
- The `date_resolved` and `status` columns of the dispute needs to be updated to reflect the decision

**TODO:**
- [x] Table definitions
- [x] Triggers
- [x] Relevant API updates

EDIT:

We decided against the use of triggers for now as the aftermath of their implementation would warrant deathpacito.

**Comment by S3BzA** [comment]
acknowledged

**Comment by S3BzA** [comment]
@vfeistel Will the API updates be handled by services? if so i'll also assign kiv or caelan.

**Comment by S3BzA** [comment]
@ZaguePrime  this table has been added to the init.sql in dev, you can update the models.
