### ISSUE TITLE
Vulnerability: Clickjacking

### ISSUE THREAD

**Issue by S3BzA** [COS301-SE-2024/Dispute-Resolution-Engine#461]
Missing anti-clickjacking protection.

Solutions:
1. **Add the `X-Frame-Options` Header**:  
   This header prevents your web pages from being embedded in iframes on other sites. Use the following values:
   - `DENY`: Prevents any site from embedding the page.
   - `SAMEORIGIN`: Allows only your site to embed the page.

   Example:
   ```
   X-Frame-Options: DENY
   ```

2. **Use the `Content-Security-Policy (CSP)` Header**:  
   A more modern approach is to use the CSP header to control iframe behavior:
   ```http
   Content-Security-Policy: frame-ancestors 'self';
   ```
   This ensures that only the same origin can load our content in an iframe.

Original Nikto output:
```
Nikto:
- Nikto v2.1.5
---------------------------------------------------------------------------
+ Target IP:          196.29.59.166
+ Target Hostname:    capstone-dre.dns.net.za
+ Target Port:        80
+ Start Time:         2024-09-25 21:23:02 (GMT2)
---------------------------------------------------------------------------
+ Server: No banner retrieved
+ The anti-clickjacking X-Frame-Options header is not present.
+ Uncommon header 'x-content-type-options' found, with contents: nosniff
+ No CGI Directories found (use '-C all' to force check all possible dirs)
+ 6544 items checked: 0 error(s) and 2 item(s) reported on remote host
+ End Time:           2024-09-25 21:25:35 (GMT2) (153 seconds)
---------------------------------------------------------------------------
+ 1 host(s) tested
```

**Comment by MichaelHorwitz** [comment]
fixed on hotfix traefik
