### ISSUE TITLE
Workflow builder ghost nodes

### ISSUE THREAD

**Issue by S3BzA** [COS301-SE-2024/Dispute-Resolution-Engine#525]
Following a specific sequence, it is possible for states that no longer exist to be referred to by existing states in a manner that could potentially break during runtime.

### Recreation (Tested on deployment: 2024-09-30)
1. My starting Workflow:
![image](https://github.com/user-attachments/assets/ac69da91-0559-4d73-b60d-9a9ce1f48510)
2. Add a node that i will then delete:
![image](https://github.com/user-attachments/assets/4d47d267-0fd6-405f-bf24-6e0330da998a)
3. After deleting said node, create a fresh node from `Node 1`
![image](https://github.com/user-attachments/assets/b8a62e3e-bd55-48f8-8075-e92100f86213)

Resulting workflow:
```json
{
  "initial": "Im not sure",
  "states": {
    "0": {
      "label": "Node 0",
      "description": "sure bud",
      "events": {
        "3": {
          "label": "trigger0",
          "next_state": "1"
        }
      }
    },
    "1": {
      "label": "Node 1",
      "description": "sure bud",
      "events": {
        "6": {                             // Ghost node <--
          "label": "trigger1",
          "next_state": "4"
        },
        "9": {
          "label": "trigger999",
          "next_state": "7"
        }
      }
    },
    "7": {
      "label": "FreshNode",
      "description": "sure bud",
      "events": {}
    }
  },
  "label": "asdf"
}
```

**Comment by MichaelHorwitz** [comment]
Should be fixed on dev

**Comment by MichaelHorwitz** [comment]
fixed on feat/workflow-polishes
