### ISSUE TITLE
Project Day

### ISSUE THREAD

**Issue by Vafdaf12** [COS301-SE-2024/Dispute-Resolution-Engine#561]
The list of things to do:
- [x] Sweets (ideally blue ones to match with our branding). Lollies were mentioned
- [x] A blue tablecloth
- [x] Designing and printing A2 posters (R125 per A2 Colour Page)
  - How many posters do we design?
  - What do we put on the posters?
  - Where do we get the posters printed?
- [x] Demo videos showcasing our app
- [x] Bug fixes that still need to be done (see other issues)

Edit:
Due to cost I reckon 3 posters will be reasonable, I recommend the Deployment Diagram as our Arch isn't too impressive. The other 2 i don't know, but I reckon an infographic on what ADR is will be a definite winner so people understand what we are doing, and then maybe a feature list?

@S3BzA Can go talk to the lady at Tasko's and see what we can do for bulk Sweets.

**Comment by ghost** [comment]
How do we feel about also giving out some accessories (pens, stickers, pins)?

**Comment by S3BzA** [comment]
@Vafdaf12 I think @MichaelHorwitz is already looking into that. His mother provides that sort of business.

**Comment by MichaelHorwitz** [comment]
@S3BzA When I checked with her last it takes a while and is pretty pricey. Could maybe get them by Friday but it's like R300 for some initilasation fee and then over and above that you start paying for the actual products
