### ISSUE TITLE
Failed end-to-end Tests

### ISSUE THREAD

**Issue by ghost** [COS301-SE-2024/Dispute-Resolution-Engine#83]
All the E2E tests fail due to it being unable to navigate to the URL. I suspect this has to do with Docker's naming convention, where instead of using `localhost` you use the name of the container, e.g. `frontend`.

Some quick googling suggested configuring the `baseUrl` variable of Cypress's configuration, and overriding it using the `CYPRESS_BASE_URL` environment variable in the action itself

**Comment by MichaelHorwitz** [comment]
Extended due to blocked by deployment
